### ISSUE TITLE
Add `DateOnly` and `TimeOnly` types

### ISSUE THREAD

**Issue by myokeeh** [Azure/azure-mobile-apps#223]
Add `DateOnly` and `TimeOnly` to Azure Mobile Service 

_Originally posted by @myokeeh in https://github.com/Azure/azure-mobile-apps/discussions/220_

**Comment by adrianhall** [comment]
Unblocked as of 5.0.0-beta.9 - not implemented yet, but the service in now .NET 6.0 only, which allows us to do DateOnly and TimeOnly on the service side.  Need to have appropriate client-side functionality, since the client is .NET Standard 2.0.  I suspect that what we will do is have a DateOnly and TimeOnly implementation in the library that we will use instead.

**Comment by adrianhall** [comment]
Spent some time on this today.  Turns out, `DateOnly` and `TimeOnly` are technically doable today.

1) Create a DateOnly or TimeOnly field on the server side, with a [JsonConverter] (Newtonsoft.JSON model) attribute that converts it to a string in the required format.
2) There is no .NET Standard 2.0 DateOnly and TimeOnly class, so you will have to make your own.  
3) You will have to write a System.Text.Json deserializer for the client side to your specific class, then add it to the SerializerSettings in the DataSyncOptions class.

Now, if you want to do things like 'releaseDate.Month > 5' in the search and have it do the "right thing" in SQL, that's more work.  The OData 8.0 library will need to support it for that to happen.

**Comment by adrianhall** [comment]
DateOnly / TimeOnly are added to service side.

Need to add DateOnly and TimeOnly support to SQLite, but it's unlikely to happen due to stamping of SQLite types.
