### ISSUE TITLE
The LINQ expression could not be translated in GetDataView()

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#255]
**Describe the bug**
The LINQ expression could not be translated in GetDataView()

**To Reproduce**
1. new project with Datasync template
2. follow [this post](https://adrianhall.github.io/azure/2021/11/10/complex-zumo-auth/) to add IAccessControlProvider<T>
3. send GET request https://localhost:44317/tables/todoitem?ZUMO-API-VERSION=3.0.0
4. See error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The LINQ expression 'DbSet<TodoItem>()
    .Where(t => __predicate_0.Invoke(t))' could not be translated ... 

**What platforms?**
* Server:
    * [x] ASP.NET Core

**Screenshots**

**Additional context**

    public class TodoItemController : TableController<TodoItem>
    {
        public TodoItemController(AppDbContext context)
            : base(new EntityTableRepository<TodoItem>(context))
        {
            AccessControlProvider = new TodoItemControlProvider();
        }
    }

    internal class TodoItemControlProvider : IAccessControlProvider<TodoItem>
    {
        public Func<TodoItem, bool> GetDataView() => model => model.IsComplete;

        public Task<bool> IsAuthorizedAsync(TableOperation op, TodoItem entity, CancellationToken token = default) 
            => Task.FromResult(true);

        public Task PreCommitHookAsync(TableOperation operation, TodoItem entity, CancellationToken token = default)
            => Task.CompletedTask;
    }

**Comment by adrianhall** [comment]
Can you confirm the version of the NuGet packages you are using in your project?  (Will assume 5.0.0-beta.8, but would like the confirmation)

**Comment by fileman** [comment]
Yes, it is beta 8, I have used the official template to reproduce the issue

**Comment by adrianhall** [comment]
Issue is that the `ApplyDataView` extension method uses Invoke, which causes a permanent client-side evaluation.

Investigations:
* How to do an automatic client-side evaluation (since someone is going to do something in the data view at some point to cause it, and then I'll have the problem again)
* How to detect client-side evaluation in EF Core (so I can alert in logging on a performance issue)

The fix for the specific situation is relatively easy.  However, want to solve the bug more generically.

Target: beta-9

**Comment by adrianhall** [comment]
Also TODO: Convert the RRatedMovieController (and/or the LegalMoviesController) in the common web service used for testing to use SQLite in-memory store.  This will slow down the tests (currently each run takes ~ 20 minutes in VS 2022), but will allow us to test the access control provider using the EF repository rather than the in-memory repository (in-memory repository returned an IEnumerable<T>.AsQueryable(), which masked the problem that is being reported).

**Comment by adrianhall** [comment]
Update: I'm doing all the changes for this bug here: https://github.com/adrianhall/azure-mobile-apps/tree/issue255 - as of right now, the bug is fixed.

However, I'm converting the tests over to use the EF Core SQLite in-memory database instead of an In-Memory repository.  The net result of this is that there are a lot of tests failing right now in an unrelated manner.  I've got approximately 3,577 tests to update, so it will be a few days before the PR for this will appear.  Hoping to have it done by Friday.

**Comment by adrianhall** [comment]
Just putting a placeholder update here.  Today was one of those cases of "Oooohhhh - I remember why I was using InMemory instead of SQLite now!!!"  SQLite has "issues" with DateTimeOffset (like, no support for), and Datasync Service relies on DateTimeOffset support to the ms accuracy.

Current adrianhall/azure-mobile-apps issue255 branch has the changes in the Microsoft.AspNetCore.Datasync.Test project, but requires the WebService to be updated to support DateTimeOffset, which is documented here: https://blog.dangl.me/archive/handling-datetimeoffset-in-sqlite-with-entity-framework-core/ - so that's the next step.

**Comment by adrianhall** [comment]
... Turns out that switching the tests over to use a SQLite db (given the constraints of the DB) is a big undertaking.  I'm going to check in the fix (assuming it hasn't actually broken anything in the tests), and then I'll file another bug to update the tests projects.

**Comment by adrianhall** [comment]
Merged in PR #260
