### ISSUE TITLE
Add Automapper based EF Repository

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#371]
**Is your feature request related to a problem? Please describe.**

I want to map certain fields so I have a DTO and Domain object.  Example, my domain object has a Guid Id but the DTO needs a string.

**Describe the solution you'd like**
An Automapper based EF Core repository would be ideal.

**Comment by fileman** [comment]
I have this case in my solution, I'm using linq to create Dto in Query method and Automapper on Create o Update.
This feature should be in an optional nuget, someone could have an automapper version constraint.

**Comment by adrianhall** [comment]
I like that idea.  Do you have the AutoMapper IRepository, or is it a custom one?  Mind me taking a look?

**Comment by henda79** [comment]
@adrianhall, I'm trying to implement something to manage this as we spoke about briefly on Gitter, but I'm struggling.

I would like to be able to use Guid's for my PK's. I could do this by modifying the code for the framework but that's less than ideal. So far I've created a separate .NET Standard 2.1 project in which I have abstracted my tables to interfaces, the idea here is to ensure correct implementation on both client and server.

Now I was interested in the AutoMapper framework and it seems thats the way you want to go. Do I need AutoMapper on both client and server ? I ask as it not possible to use ITableData on the client, I suppose I'm a bit confused what goes where, I've spent the day on this but not getting anywhere.

**Comment by adrianhall** [comment]
Inevitably (at least for any non-basic situation), the models on client and server are different.  They have different requirements.  The server side usually has additional server-only fields and has attributes describing the EF side of things (indices, etc.) that are not available on the client side.

Best idea is to create an interface in the shared project:

``` csharp
public interface IModel
{
    string MyProperty { get; set; }
}
```

and then have a implementation in each side:

``` csharp
public class ServerModel: EntityTableData, IModel
{
    [Required, Index("Index_MyProperty"]
    public string MyProperty { get; set; }
}
```

and

``` csharp
public class ClientModel: DatasyncClientData, IModel
{
    public string MyProperty { get; set; }
}
```

Now, in your case, you have an additional problem of needing a "Guid" field instead of an Id field.  You can use the existing EntityTableData, potentially:

``` csharp
public class MyEntityTableData : EntityTableData
{
    [NotMapped]
    public override string Id
    {
        get => MyId.ToString("N"),
        set => MyId = Guid.Parse(value)
    }

    [Column("id")]
    [JsonIgnore]
    public Guid MyId { get; set; }
}
```

The MyId field is stored in the database as Id and never sent across the wire, whereas the Id field is not stored in the database, but is sent across the wire.  When you get/set the Id field, it actually gets/sets the MyId field using a Guid parser.

This is where I would start, rather than waiting for the Automapper support (which is the "right" way to do this architecturally - this is a poor mans mapper)

**Comment by henda79** [comment]
@adrianhall, thanks for the quick reply.

The first part is exactly what I have, different implementations of the interface on client and server.

I had started implementing AutoMapper but got a bit confused as it needs to know about both client and server concrete types to work, does it not ? and this just seems to duplicate code even more as the client types would need to be available to the server.

The reason for the use of the Guid, is this is a legacy project and the DB schema was used on Windows Mobile and Merge Replication. The problem here is that many of the tables (50+)  reference each other using Guid's, so aside from the PK, which were a manually mapping here, there are many others (FK's).

I'm not adverse to changing things around but I though using 32 byte strings would result in bad performance and if anything a int would be a better idea.

**Comment by adrianhall** [comment]
The mobile world is different - you have to use globally unique IDs in mobile work - ints don't cut it as it is too easy to get an ID collision.

The client does not need to use AutoMapper.  The automapper is only supported on the server side.

**Comment by fileman** [comment]
In my solution I have server-side Entity with Guid Id and client-side String Id (using CustomIdGenerator)

In DatasyncController use a custom DatasyncInMemoryRepository with:

1.  Queryable get Dto from EntityRepository and with linq map Entity to Dto 
```
      form table 
      ... 
      select new Dto { 
          Id = entity.Id.ToString(), 
          ...
      }
```
2.  CRUD methods use Automapper from Dto to Entity and then use CRUD EntityRepository

**Comment by henda79** [comment]
So what would AutoMapper be used for ?

I implement a table on the client using the interface shared between client and server, this is the domain model ? When we want to sync with the server, do we send the domain model or a DTO, if a DTO, is this just a lite version of the domain model ?

So now the server has this, what does it use AutoMapper for ? We already have a concrete implementation of the shared interface for that table.

I must be missing something.

**Comment by adrianhall** [comment]
There are three models to consider:

1. Client-side DTO - this is the model that is received from the server as JSON and stored in the SQLite databae.
2. Server-side DTO - this is the model that is used to send the data to the client, or receive data from the client.  It may have additional fields (like user ID) that are not sent to the client (thorugh JsonIgnore attribute).  You may also want to add attrbiutes for specifying model requirements (like Required, MaxLength, etc.)
3. Server-side Model - this is the model that is used by Entity Framework to store or retrieve data in the database.  It has Key, Index, and other EF-specific attributes on it.

For simple cases (I classify the Guid translation as simple - see my methodology above) you don't need AutoMapper.  For more complex cases (or maybe because you want to), you use AutoMapper to provide the mapping between models 2 and 3 - the server side models.

**Comment by henda79** [comment]
Thanks for taking the time to explain, but in your TodoApp server example there is only one model, the one derived from EntityTableData, or is that because there is no conversion needed ?

**Comment by adrianhall** [comment]
There is no conversion needed, so the domain model == DTO.

**Comment by henda79** [comment]
@adrianhall , the string - Guid conversion works for inserting the item, but If I try to update I get an error 400, Bad Request. I've done a bit of debug and its because the Id's don't match.

![image](https://user-images.githubusercontent.com/67002466/173245918-7c630394-872d-48f0-8bb0-007c4502fc29.png)

![image](https://user-images.githubusercontent.com/67002466/173245946-687f790c-94e7-47ef-b042-9bd4329ccab2.png)

You can see from these 2 images that the Id does match. I did a bit more digging and because the TableController is generic and converts the item back to ITableData, the Id is then somehow null.

![image](https://user-images.githubusercontent.com/67002466/173246055-3534b47c-b01a-47d2-913a-364979054384.png)


Would I be better off just using strings for table PK's and FK's ?

**Comment by henda79** [comment]
Looks promising, I'll have a look.

**Comment by henda79** [comment]
> ```cs
> MappedTableRepository
> ```

This example does not work as `MappedTableRepository<TEntity, TDto>` does not implicitly convert to `IRepository<TDto>` even with an explicit conversion it still fails.

At the moment I'm not sure how to fix it.
