### ISSUE TITLE
Why add handler mapper for all platforms?

### ISSUE THREAD

**Issue by LKujala** [Azure/azure-mobile-apps#464]
**Is your feature request related to a problem? Please describe.**
Reviewing code in sample against code in MAUI documentation; just wondering why the sample code was written in a particular manner.
in TodoApp.Maui/App.Xaml.cs a AppendToMapping handler is added.
the lambda is populated for Windows and is otherwise empty.

**Describe the solution you'd like**
1 - Why add an empty handler for non-windows MAUI apps at all? the code seems to handle an issue specific to windows code.

2 - why add the handler in the base App.xaml.cs code instead of adding it to the windows specific App.xaml.cs code?

Just curious about the design choice that was made.

**Comment by adrianhall** [comment]
The problem with doing 12 different samples for various frameworks is that I'm not equally versed in all frameworks.  This is true for Avalonia as well as MAUI (which is only that way because I started working on it during betas).  As a result, some of the tutorials are less "the right way" and more "the way I could make them work".

As always, I am quite willing to take a PR for updated tutorial code as long as it does not require a change to the tutorial.  The way I take PRs is that I'll download the code in the PR and then run through every single sample to make sure they still work without changes.  (this means, of course, that validating a change to the samples takes longer).

**Comment by LKujala** [comment]
I understand and appreciate the issue with multiple platforms (which is why I am reviewing MAUI).
when reviewing code, I like to understand why the author wrote it in a particular manner; especially if it "seems" like there are different ways to write it. every line of code matters!

**Comment by adrianhall** [comment]
In this particular case, the code was copied from a sample elsewhere that I was pointed to by one of the MAUI engineers as the method for setting the initial size of the window on the Windows platform.  Since it did what I wanted it to, I literally just copy/paste the code.

**Comment by LKujala** [comment]
Cut and Paste, thou art my friend.
thx
