### ISSUE TITLE
I followed the examples and it's working but how do I dev and test locally ?

### ISSUE THREAD

**Issue by stephenhauck** [Azure/azure-mobile-apps#471]
I need to work offline at times and it's just a little quicker to test and develop locally.
How do I test "Azure mobile apps" offline ?

**Comment by adrianhall** [comment]
1) Set up the server to run locally with a local instance of SQL Server.
2) Run the app against the server (generally, https://your-ip:your-port as the client - don't use localhost or 127.0.0.1 because those refer to the emulator/simulator rather than the underlying host)

It's just an ASP.NET Core application and a mobile app talking to it.  Standard mobile app with local backend stuff applies.

**Comment by stephenhauck** [comment]
But will the Azure sync work as well ?

**Comment by adrianhall** [comment]
The data on the device will by synchronized with the data in the SQL Server local instance instead of Azure SQL.

**Comment by stephenhauck** [comment]
I am a little confused ... Is this also something we could run on prem in an enterprise instead of Azure ?

**Comment by adrianhall** [comment]
Certainly.  Just to repeat - this is just an ASP.NET Core application talking Entity Framework Core to a database of your choice.  There is no reason you can't run it anywhere you choose as long as the clients can connect to the service.
