### ISSUE TITLE
Perfomance

### ISSUE THREAD

**Issue by gptucci** [Azure/azure-mobile-apps#480]
**Is your feature request related to a problem? Please describe.**
I've verified that perfomance is a issue !

**Describe the solution you'd like**
I've tried to compare Microsoft.Datasync.Client.SQLiteStore and sqlite-net-pcl in a XF env.
I'ive verified that sqlite-net-pcl is 3 times more perfomant

**Additional context**
I love Datasync ! Tnx. I just wish it were faster

**Comment by adrianhall** [comment]
Both sqlite-net-pcl and SQLiteStore use sqlitePCLRaw underneath - they are both abstractions.  The data store used for synchronization is not a general purpose store but has additional code for the specific function for synchronization.  Using sqlite-net-pcl will NOT be more performant - the same underlying issues will show up.

Since the SQLiteStore is based on the AbstractStore (which is in the main package), you can, of course, re-write the SQLiteStore  to use sqlite-net-pcl.  If you do, please let us know!  We can then do an apples-to-apples comparison.  Since we already have a SqlitePCLRaw based driver, I won't be taking this feature request.
