### ISSUE TITLE
WinUI authentication sample always returns IsAuthenticated false

### ISSUE THREAD

**Issue by cveld** [Azure/azure-mobile-apps#490]
## Describe the bug

We followed the instructions on 
https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/winui/authentication.md

but:

```c#
result = await identityClient
                    .AcquireTokenSilent(Constants.Scopes, accounts.FirstOrDefault())
                    .ExecuteAsync();
```
always yields an `AuthenticationResult` with a `ClaimsPrincipal` where the `IsAuthenticated` property returns `false`.

Is this expected?

We have added the following logic to enforce `IsAuthenticated` to `true`:

```c#
var claimsIdentity = new ClaimsIdentity(claims: authenticationResult.ClaimsPrincipal.Claims, authenticationType: "nativeapp");
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
```

The documentation of `ClaimsPrincipal`'s `IsAuthenticated` property states:
true if the `AuthenticationType` property is not null or an empty string.

Reference: https://learn.microsoft.com/en-us/dotnet/api/system.security.claims.claimsidentity.isauthenticated?view=net-6.0

We created an issue on the docs repo:
https://github.com/MicrosoftDocs/azure-dev-docs/issues/914
but @adrianhall asked us to create an issue in this repo instead.

## What platforms?
      <PackageReference Include="Microsoft.Identity.Client" Version="4.47.2" />
Target framework: net6.0-windows10.0.19041.0

**Comment by adrianhall** [comment]
I'll walk through the entire tutorial again on Friday.  Until then, can you please dump out the value of the result?  (feel free to obfuscate GUIDs but starring out the middle sets of digits so I recognise they are GUIDs but can't use them).

**Comment by adrianhall** [comment]
So, let's go through the findings of this:

1) There is a bug in the code, but it isn't about the IsAuthenticated. - the code in the sample does not use the "IsAuthenticated" flag - we use the existance of the access token as a determiner of authentication.  So the original report isn't relevant.  If you need IsAuthenticated in your code, you need to file an issue with MSAL and pursue it there.

2) There IS a bug in the code around the DisplayErrorAlertAsync() method.  Basically, if you cancel out of the authentication box or GetAuthenticationToken otherwise returns an error, then the DisplayErrorAlertAsync() method is called and that throws.  I need to do an investigation on this, but it will result in a new issue here.

3) There is also a bug in the docs - in the WinUI sample, I tell you to reference the TodoApp.WPF project, which is wrong.  I'll submit a correction today.

This issue itself is closed at this point, as the reported issue is not an issue with the sample or tutorial.
