### ISSUE TITLE
How to manage offline mode and authentication?

### ISSUE THREAD

**Issue by Goldstrike** [Azure/azure-mobile-apps#491]
After having some troubles with the TodoApp project, I've finally followed all the steps and all works fine.

However I would like to know if there is a way to manage the offline mode with authentication?

For example, if I enable the Airplane mode on the devices before launching the app, there is an Exception during the call to `await _table.PushItemsAsync();` in the `RemoteTodoService`.

On the devices, we also display errors:
- on **iOS**, there is a popin "RefreshItems - No such host is known"
- on **Android**, there is a popin "RefreshItems - Push operation failed. See the PushResult for details."

Is there a way to manage the offline mode in case of no network, with enabling the authentication when network is available?

**Comment by adrianhall** [comment]
When you use `PushItemsAsync()`, you are explicitly telling the app to connect to the remote service and push pending items to the service.  In Airplane mode, this generates an error - so what you are seeing is exactly right.

What I see most people doing is to monitor for network connectivity.  For Xamarin, check https://devblogs.microsoft.com/xamarin/easily-check-mobile-device-connectivity-with-xamarin-essentials/ - for MAUI, check https://learn.microsoft.com/dotnet/maui/platform-integration/communication/networking

**Comment by Goldstrike** [comment]
So there is no way to recover data from local database when there is no internet access?

**Comment by adrianhall** [comment]
As long as you are not using push/pull - the data is available  Just use an OfflineTable<T> instead of a RemoteTable<T>.

When you are using an OfflineTable<T>, the data is available from the SQLite database.  You don't need internet access.   The idea would be

1. Use PullItemsAsync() to pull data from the remote server into the offiline database.
2. Go offline (airplane mode)
3. Make any changes you want to make - everything works just fine (searching, sorting, adding, removing, etc.) but against the SQLite database.
4. Go back online
5. Call PushItemsAsync() / PullItemsAsync() to send the changes you made to the remote service and get any changes that were made to the remote service while you were offline.

I've got developers who have written apps that are offline for a month at a time and then re-sync at the end.   It's a case of recognizing that you are going to be offline and ensuring you don't call the push/pull routines when you are not connected to the internet.

**Comment by Goldstrike** [comment]
Thanks for your reply.

Yes finally it was easy, I've just did this for a small test and this works fine:
```
public async Task RefreshItemsAsync()
{
    await InitializeAsync();

    if (Connectivity.NetworkAccess == Xamarin.Essentials.NetworkAccess.Internet)
    {
        // First, push all the items in the table.
        await _table.PushItemsAsync();

        // Then, pull all the items in the table.
        await _table.PullItemsAsync();
    }

    // Remote table doesn't need to refresh the local data.
    return;
}
```

It was a misunderstanding from my side, as `GetItemsAsync()` can be called without any connection.

**Comment by adrianhall** [comment]
Great that you got it solved!
