### ISSUE TITLE
Support Cosmos DB

### ISSUE THREAD

**Issue by fraxedas** [Azure/azure-mobile-apps#53]
In the docs [Create a .NET backend using the Azure portal
](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk#create-a-net-backend-using-the-azure-portal) you are describing how to use a SQL Database.
Please support Cosmos DB as a database option.

**Comment by elamalani** [comment]
@fraxedas Thanks for using Azure Mobile Apps. At this time, we don't plan to support CosmosDB as a database option since we are not actively developing new features. Please refer to the ReadMe file that talks about the future of Azure Mobile Apps.

https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps

**Comment by fraxedas** [comment]
Thanks @elamalani 
I'll close the issue then.
