### ISSUE TITLE
Relationship Support

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps#6]
Support for relationships is one of the most commonly requested features for Azure Mobile Apps. This issue needs to be developed into a full feature writeup, but for now it is a placeholder that we can link other relationships related issues to.

**Comment by phvannor** [comment]
One common way to deal with relationships (at least read only) is to get the related entities together using $expand.  As shown in the iOS SDK, we can then update the local store to spread the entities into their own tables for easier querying/etc once in the local store.

Storing many tables in one local store upsert allows us to ignore the transaction problem.  To move beyond the above, we need to figure out how to pull the transaction above the store, so we can begin, upsert A, delete, etc, end transaction cleanly.  

The problem lies in coordinating the upsert with dirty data.  The store doesn't have the knowledge to say if child item A is dirty, should it be saved/etc.  So once you move from read only to editing w/relationships the above needs more work.

The Push portion is a little more straightforward for the client.  Mainly we need some logic that can pick up the items that need to go together, and an endpoint that can process those X items together as a single transaction.  The server portion is more complicated in figuring out how to tie that endpoint into existing server side scripts.

**Comment by meoz** [comment]
Hi, I am using the IOS SDK and understand that Core Data relationships are not supported yet. The Core Data shema I'm using contains several relationships between different tables. I would want to go in test asap using Azure mobile apps for cloud syncing. Is there an alternative I can use to model the relationships in Azure ? Do we need to remodel relationships between tables using foreign keys ?

**Comment by danderson00** [comment]
I'd highly recommended avoiding the approach of attempting to update multiple related entities with a single call to insert or update, i.e. trying to figure out which child entities were modified / added / removed. This is a recipe for disaster.

I'd recommend users update each entity individually, i.e. If an entity called Parent has a new Child record added, the Child record should manually be inserted with the appropriate foreign key value.

**Comment by lindydonna** [comment]
@danderson00 Is that a comment on the related GitHub issue https://github.com/Azure/azure-mobile-apps-net-client/issues/183, or on Phil's previous reply above?  Or both?

Either way, I agree, particularly because Entity Framework does not support this scenario, which is known as the "detached object graph" problem. E.g. see http://stackoverflow.com/questions/14098600/many-to-many-relationships-not-saving

**Comment by drungrin** [comment]
@danderson00, @lindydonna 

#183 relates only to filtering the pull.

**Comment by elamalani** [comment]
Hey everyone, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now.

**Comment by gonzobrains** [comment]
> Hey everyone, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now.

Since no new features are planned for the foreseeable future, what project will be replacing this one for offline-sync purposes?

**Comment by elamalani** [comment]
@gonzobrains We are still in the early phase to determine the next product that would replace Azure Mobile Apps. Please look out for more information on the docs or GitHub repos, we will update them once we have a concrete plan. Thanks!

**Comment by ltaljaard** [comment]
@elamalani I have implemented my own solution on top of Azure Mobile Apps to support relational data. It results in one pull operation for each table in your relational db so it's not optimal. And it requires some table-specific coding (which can be made generic with a bit of work). The multiple pulls are due to the inherent inner workings of the Mobile Apps solution. I believe this is the best that one can do in its current incarnation. Let me know if you are interested. Perhaps you can take what I've done and tweak Mobile Apps to support a single pull for all. If you can do that then you might be able to support relational syncs quite well.
