### ISSUE TITLE
Unable to open database connection

### ISSUE THREAD

**Issue by JarFrank** [Azure/azure-mobile-apps#637]
## Describe the bug

I am facing an issue with initializing the sqlite database in my project. I am not sure if it is related to permissions or library. I observed that if I initialize the `OfflineDataSync` class before `base.OnCreate(bundle);` in `MainActivity.cs`, then everything works fine. But if I initialize it later in the project, I get an error `Unable to open database connection`.

```
{Microsoft.Datasync.Client.SQLiteStore.SQLiteException: Unable to open database connection to 'file://localhost/data/user/0/com.myproject.test/files/offline8.db?mode=rwc': 14 unable to open database file
  at Microsoft.Datasync.Client.SQLiteStore.Driver.SqliteConnection..ctor (System.String connectionString) [0x0007d] in <fe2451a3f2d14c6b95d9b69a51ff8d1f>:0 
  at Microsoft.Datasync.Client.SQLiteStore.OfflineSQLiteStore..ctor (System.String connectionString) [0x00044] in <fe2451a3f2d14c6b95d9b69a51ff8d1f>:0 
  at MyProject.Application.Services.OfflineDataSync`1[TTable].InitializeAsync () [0x001fc] in C:\my-path\MyProject.Application\Services\OfflineDataSync.cs:82 }
```

## What platforms?

* Server (ASP.NET Framework, ASP.NET Core, NodeJS):
  * Microsoft.Datasync.Client 5.1.2
  * Microsoft.Datasync.Client.SQLiteStore 5.1.2
  * MvvmCross 8.0.2

* Client (.NET, JavaScript, iOS, Android):
  * Android 10,11,12

**Comment by adrianhall** [comment]
Is OfflineDatasync<T> a singleton?

Do you lock against multiple threads trying to initialize at the same time?

The error message indicates that the application cannot open the database file.  This can be because:
a) Your app doesn't have permission to open the file.
b) Your app has already opened the file somewhere else.
c) The directory you are specifying does not exist.
d) Any number of I/O issues (which is unlikely).

**Comment by JarFrank** [comment]
Thank you for your quick response. I appreciate your help in resolving this issue.
Yesterday, I did some more investigation and I found something interesting. Let me share it with you.

Currently, in our application, we are using sqlite database `Container.sqlite` as a primary source. We want to gradually move to Datasync approach. To populate previous database, we are using `abp push` (root) to push the dev database to the emulator. After pushing, we change the permission, group and owner according to the application and it works as expected.

However, I discovered that the issue persists only when we do the step with `abp push` and after that the datasync library sotp working properly. This seems to cause some conflict. Without `abp push` datasync library works as expected.
Do you have any idea why this happens and how we can fix it?

As a workaround:
1. We opened the app and logged in. This created an empty `Container.sqlite` file in the app's directory
2. We moved our dev database `Container.sqlite` to android's temp location
.\adb.exe push /storage/emulated/0/Android/data/com.myproject/Container.sqlite
3. We replaced the content of the empty database file with the content of our dev database file using the cat command
cat /storage/emulated/0/Android/data/com.myproject/Container.sqlite > /data/user/0/com.myproject/files/Container.sqlite

**Comment by adrianhall** [comment]
Did you close and force quit the app between moving it out of the way?

**Comment by JarFrank** [comment]
I rebuilt and recompiled the application

**Comment by adrianhall** [comment]
You are working in unsupported territory,  I have suspicions, but the abp stuff you are doing don't honor locks, which are obviously present.

Your better mechanism would be to have an "import from JSON" capability.  Instead of copying in the Container.sqlite, dump the container as a (set of) JSON documents, then use the methods in the sqlite offline store to inject the records into the managed sqlite database.  You may have to fork the offline store to expose the appropriate methods.
