### ISSUE TITLE
PurgeItemsAsync with DiscardPendingOperations Unexpected Behaviour

### ISSUE THREAD

**Issue by wedgeley** [Azure/azure-mobile-apps#823]
The **PurgeItemsAsync** method of **OfflineTable** accepts a query and **PurgeOptions**, allowing pending operations to be discarded.

## Expected Behaviour
I expected it to discard operations for the entities in the query.

## Actual Behaviour
In release 6.0.5 and earlier it purges all operations in the OperationsTable for the specified table.

## Suggested Change
In **Microsoft.Datasync.Client\Offline\SyncContext.cs**, **DiscardTableOperationsAsync** could be extended or overloaded with a method that takes a "query" parameter. **PurgeItemsAsync** could then use this method to be more selective in the pending operations it deletes.

**Comment by adrianhall** [comment]
Smells like a bug - I'll take a look after Ignite.

**Comment by adrianhall** [comment]
Since the query parameter for the PurgeItemsAsync is totally different from the operations queue, this is going to be "hard".  I'll need to adjust the query ahead of time to only return the IDs for the purged items, then remove the operations based on tableName and ItemId from both the table and the operations queue.

This is much more of a major change that first envisioned, and it's a behavioral breaking change.  I agree with you that this is what should be happening.  I'm just unsure of the timeline right now.

**Comment by wedgeley** [comment]
> Since the query parameter for the PurgeItemsAsync is totally different from the operations queue, this is going to be "hard". I'll need to adjust the query ahead of time to only return the IDs for the purged items, then remove the operations based on tableName and ItemId from both the table and the operations queue.
> 
> This is much more of a major change that first envisioned, and it's a behavioral breaking change. I agree with you that this is what should be happening. I'm just unsure of the timeline right now.

Yes, I can see it is an awkward one. It caught us out, but we've been able to code around it so it isn't a priority for us.

**Comment by adrianhall** [comment]
Since you have worked around it, I'm going to close this for v6.  (If anyone is having issues that haven't reported it - let me know in a new issue).

I'll fix this in v8.
