### ISSUE TITLE
Allow pull of single item 'PullItemAsync(itemId)'

### ISSUE THREAD

**Issue by dylan-mills** [Azure/azure-mobile-apps#831]
**Describe the solution you'd like**
For implementations where objects are pulled on demand rather than in bulk, it would be nice to be able to pull a single item that takes advantage of `TableController.ReadAsync()` rather than `TableController.QueryAsync()`. For some databases the cost of Read vs Query is likely similar, but for others (Cosmos) a read is significantly cheaper - 1 RU regardless of the size of the data object. I understand cosmos may only partially supported in the future, but this would still be helpful.

Here is a rough sample of what I am looking for _(not tested or compiled)_:
https://github.com/dylan-mills/azure-mobile-apps/commit/eb8d78b6f79294657db3b87afcb26ba8dcf900b0

I can spend some more time on this normalizing shared code and adding tests if you are open to the change.

**Describe alternatives you've considered**
I can create a query with the id included, but this is not as cost effective.

**Additional context**
N/A

Sorry for all the issues, should have tried to go to Ignite so I could have discussed all these thoughts in person :)

**Comment by adrianhall** [comment]
This would most definitely not be “better” - I get that you are trying to minimize RUs on Cosmos, but that is not the concern for the sync library.  The concern is minimizing network time (time to sync) or balancing time to sync against local storage.

We are getting into the realm of custom sync solutions rather than a generic sync service.
