### ISSUE TITLE
Data model needs to inherit EntityTableData

### ISSUE THREAD

**Issue by niklashaudek** [Azure/azure-mobile-apps#835]
Hi @adrianhall ,

is it possible to use a single datamodel for usage in serverside and clientside datasync? I'm currently facing the problem that I want to have a single model source for both parts of my application, however AspNetCore.Datasync forces me to inherit my model not only from `ITableData` but from `EntityTableData` as the type is challenged in line 38 of `EntityTableRepository.cs`. The problem is that referencing this project in my base project which holds the models causes my .Net Maui Application not to launch as there are server side references included.

Can we discuss a possible solution? Thanks in advance!

**Comment by adrianhall** [comment]
No, it isn’t, and when you sit down and think about it, that’s ok.  The server side data model generally has more stuff - who initially wrote the record, who is allowed to download it, etc.  It also has attributes that only have meaning on the server side because it’s linked to EFCore or LiteDb or whatever.    You’d have to bring all those libraries into your client application and some of them are incompatible with iOS/Android apps.

The client model also has a functional change from the server side model.  The server side model version is a byte[] because of the way EFCore implements the [Timestamp] attribute.  However, this is received on the client side as an opaque string.  Another common change is to change the Id field from a string (which is required on the client side because you don’t know anything about the server implementation) but translated to a GUID or similar on the server side so that it is stored properly in the database.

It’s a nice idea, and I’ve lost count of how many times I’ve been asked.  However, it’s just not possible.

**Comment by niklashaudek** [comment]
Hi Adrian, thanks a lot. What about foreign key relationships on the client side? How do they get automatically generated in the SQLite DB? Because adding a property like "SpecialType" and string and property like "SpecialTypeId" doesn't solve this issue, like with EFCore on the server side? For me it would be perfectly fine to just have the property and DataSync does the rest on the client side? Am I using it wrong? Thanks in advance!

**Comment by niklashaudek** [comment]
How do you solve this?

**Comment by adrianhall** [comment]
Short version - you structure your synchronized data models so they are not required.

Each table is individually synchronized, and it has to be that way because the network may go away at any point (there is a reason you are using offline instead of caching, which is an easier problem to solve).  So there can be no inherent linkage between the various tables you synchronize.

V8 will move over to Entity Framework Core to access the offline tables.  This means you can do complex joins between the tables using LINQ.  HOWEVER (and it’s a big however) the tables will still be individually synchronized, so you still will need to structure your tables to have no foreign keys.
