### ISSUE TITLE
EntityTableRepository verifying entity type in constructor

### ISSUE THREAD

**Issue by Brenki78** [Azure/azure-mobile-apps#869]
In EntityTableRepository constructor is check whether the entity type is derived from EntityTableData or ETagEntityTableData. It would be better to check whether the entity type is implementing ITableData interface only, like this:

`if (!typeof(ITableData).IsAssignableFrom(typeInfo))
{
    throw new InvalidCastException($"Entity type {typeof(TEntity).Name} is not a valid entity type.");
}`

The problem in our case is that we have data model defined in separated project library and we would like to have it as light as possible. That is why we are referencing 'Microsoft.AspNetCore.Datasync.Abstractions' package in our data model library project and there is defined only the ITableData interface. 
Our quick fix was to implement whole EntityTableRepository on our own with the only change as you can see in mentioned code snippet. But for the future it may be hard to maintain with the new versions of the azure mobile apps packages for us.

**Comment by adrianhall** [comment]
This is a deliberate design decision.  The EntityTableData class provides specific EF related attributes on the various components that are required for the proper running of the service.  One of these is [RowVersion] which is required and available only in the EF Core packages.  So you have to bring in EF Core anyhow.

This is not something we are going to fix as it is "by design".
