### ISSUE TITLE
TableController.EntityIsInView throws exception using navigation properties

### ISSUE THREAD

**Issue by Mikozans** [Azure/azure-mobile-apps#873]
## Describe the bug

Calling the TableController.ReadAsync method throws an exception when GetDataView method returns an expression which uses navigation properties.

It works fine when QueryAsync is called.

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at lambda_method2899(Closure, GenProyectos)
   at Microsoft.AspNetCore.Datasync.TableController`1.EntityIsInView(TEntity entity)
   at Microsoft.AspNetCore.Datasync.TableController`1.ReadAsync(String id, CancellationToken token)
```

## To Reproduce

Create an expression in GetDataView with navigation properties.

## Expected behavior

Allow to use navigation properties to filter and don't throw an exception.

## What platforms?

* Server:
  * Version of dotnet being used to compile? .Net8
  * Library versions? 6.0.7
  * What database are you using? Sql Server

**Comment by adrianhall** [comment]
This is not something that can be fixed.  It’s, unfortunately, a limitation of the underlying LINQ and OData libraries that we rely on.

Recommendation is to look at a custom IRepository implementation where the AsQueryable() method returns what you need.

**Comment by asierpn** [comment]
Hi @adrianhall , If we apply the GetDataView expression to the AsQueryable() method of the custom repository, it will be applied twice in the QueryAsync method of the TableController.

To avoid this, we will modify the query used in the LookupAsync and LookupUntrackedAsync methods of the EntityTableRepository using the GetDataView method of the AccessControlProvider, but using complex expressions to filter data in the GetDataView is a very common scenario that should be handled correctly by the library without any custom modifications. It is very common for us to have a Permissions details table attached to entities such as Projects, Files, etc. containing the users and roles that are allowed to see or manage the object.

**Comment by adrianhall** [comment]
You miss the point.  

In the QueryAsync() method, we use repository.AsQueryable().ApplyDataView().ApplyDeletedView() to get the IQueryable.  We then apply the filter from the OData search and that’s the data that is returned.  .ApplyDataView() uses GetDataView() from the AccessControlProvider.  This is equivalent of applying three distinct expressions as Where clauses along with the other OData primitives (like select, order by).

This is, in other words, all LINQ.  The library is limited by LINQ capabilities and by what the OData library can do with LINQ.  LINQ is powerful stuff, so the limitations are considered acceptable.  However, as you probably know, you can write LINQ that just doesn’t work.

You can create a new repository that takes an IHttpContextAccessor as an argument and returns the right data from the repository and skip the data view from the AccessControlProvider (GetDataView should return null).   That way you are operating with a DbSet<T> instead of an IQueryable<T>, which shouldn’t matter but you’ve likely found a corner case where it does.  You can even inherit from EntityTableRepository<T> and just override the one method if you like.

**Comment by asierpn** [comment]
Yes, because I wanted to continue using the GetDataView() method of the IAccessControlProvider, I solved it by creating my custom IRepositoryDataView:

```
public interface IRepositoryDataView<TEntity> where TEntity : class, ITableData
{
  Expression<Func<TEntity, bool>> GetRepositoryDataView();
}
```

We implement this interface in our BaseTableController and the parent controller instance is referenced by our CustomEntityTableRepository, so we can use it to filter data:

```
private Expression<Func<TEntity, bool>> DataView => _controller is IRepositoryDataView<TEntity> repositoryDataView
  ? repositoryDataView.GetRepositoryDataView()
  : null;

public IQueryable<TEntity> AsQueryable() => DataSet.ApplyDataView(DataView);

internal Task<TEntity> LookupAsync(string id, CancellationToken token = default)
        => DataSet.ApplyDataView(DataView).FirstOrDefaultAsync(x => x.Id == id, token);

internal Task<TEntity> LookupUntrackedAsync(string id, CancellationToken token = default)
        => DataSet.ApplyDataView(DataView).AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, token);
```

It would be better if this scenario was supported by the library, but it works this way.

**Comment by adrianhall** [comment]
Can you provide a full example of what needs to be supported?

I will add it to the test list (much like I am adding the int-id to mobile-id test) to ensure the case works; that at least allows me to figure out what changes I may need to make here.

**Comment by asierpn** [comment]
To keep it simple, I added this class to the TodoItem sample:

```
  public class TodoItemPermissions : EntityTableData
  {
      [Required, MinLength(1)]
      [ForeignKey(nameof(TodoItem))]
      public string TodoItemId { get; set; } = "";
      [JsonIgnore]
      public virtual TodoItem TodoItem { get; set; }

      [Required, MinLength(1)]
      public string UserId { get; set; } = "";
  }
```

And modified the TodoItem class:

```
    public class TodoItem : EntityTableData
    {
        [Required, MinLength(1)]
        public string Title { get; set; } = "";

        public bool IsComplete { get; set; }

        [JsonIgnore]
        [InverseProperty(nameof(TodoItemPermissions.TodoItem))]
        public virtual ICollection<TodoItemPermissions> Permissions { get; set; }
    }
```

Finally I've modified the TodoItemController:

```
  [Route("tables/todoitem")]
  [Authorize]
  public class TodoItemController : TableController<TodoItem>, IAccessControlProvider<TodoItem>
  {
    public TodoItemController(AppDbContext context)
        : base(new EntityTableRepository<TodoItem>(context))
    {
      AccessControlProvider = this;
    }

    public Expression<Func<TodoItem, bool>> GetDataView()
    {
      string? userId = User.Claims.Where(s => s.Type == "preferred_username").Select(s => s.Value).FirstOrDefault();
      return s => s.Permissions.Any(p => p.UserId == userId);
    }

    public Task<bool> IsAuthorizedAsync(TableOperation operation, TodoItem entity, CancellationToken token = default)
    {
      return Task.FromResult(true);
    }

    public Task PreCommitHookAsync(TableOperation operation, TodoItem entity, CancellationToken token = default)
    {
      if (operation == TableOperation.Create)
      {
        string? userId = User.Claims.Where(s => s.Type == "preferred_username").Select(s => s.Value).FirstOrDefault();
        if (userId != null)
          entity.Permissions = new List<TodoItemPermissions> { new TodoItemPermissions { UserId = userId } };
      }
      return Task.CompletedTask;
    }
  }
```

This code causes the exception in the EntityIsInView method when calling to ReadAsync, DeleteAsync, PatchAsync or ReplaceAsync methods.

**Comment by adrianhall** [comment]
I bet I know what is happening here :-)  I'll do a little investigation to support this.

Basically, when you do a .FindAsync() on a DbSet, it doesn't include navigation properties.  You need to use .Include - so, current EF (which doesn't support Navigation) uses

```csharp
var item = DataSet.FindAsync(new [] { id });
```

whereas, for it to return navigation properties, you have to use

```csharp
var item = DataSet.Include(x => x.Permissions).SingleOrDefaultAsync(x => x.Id == id);
```

I've, of course, removed cancellation and the like.  Basically, Permissions isn't available, and you need those to do your filtering.

I think the best option here is to allow inheritence from EntityTableRepository so you can override the AsQueryable(), etc. with your own methods.  For example, no reason why I can't make LookupUntrackedAsync() be protected instead so that you can redefine it.  Then you are doing an intherited class from EntityTableRepository; something like:

```csharp
public class MyRepositoryWithPermisstions: EntityTableRepository<MyDbModel>
{
    public MyRepositoryWithPermissions(DbContext context) : base(context)
    {
    }

    protected Task<TEntity> LookupUntrackedAsync(string id, CancellationToken token = default)
            => DataSet.Include(x => x.Permissions).AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, token);
}
```

I think that would make the process of writing derivative repositories easier. 

What I can't do is "make navigation properties work out of the box" - firstly, they contain secrets and if you don't JsonIgnore them, you are in for a world of hurt on the client side.  This makes adding/removign a navigation property a breaking change on your client.  Secondly, I have to list all the navigation properties all the time, resulting in less efficient SQL and the resulting performance degradation for no reason.

Would this work?

**Comment by asierpn** [comment]
Currently we have all our navigation properties marked with JsonIgnore, so this will not be a problem for us, but I agree that the idea of "making navigation properties work out of the box" is not a good idea.

Allowing inheritance from the EntityTableRepository can be useful in this and many other scenarios, but for this scenario I prefer the option of using the IAccessControlProvider.GetDataView directly at the IRepository level to filter the data before it comes from the database. Using the Include approach has an issue if the EntityTableRepository throws a ConflictException or a PreconditionFailedException containing an object that the user should not see in any way.

**Comment by adrianhall** [comment]
TO DO:
- EF Core repository to use protected / public virtual as appropriate to allow for over-riding.
- Suggest bringing the new EF Core repository from v8 since it supports more database types.
- Bring EF Core tests from v8 if we do this as we can do live testing of the EF Core repository.

This is a breaking change, so need to number 6.1.0 release.

**Comment by adrianhall** [comment]
> Using the Include approach has an issue if the EntityTableRepository throws a ConflictException or a PreconditionFailedException containing an object that the user should not see in any way.

Unfortunately, you don’t get it both ways.  Since the same value is used for both including in the conflictexception as to check for visibility, you either need to set things up accordingly (jsonignore, etc.) or do the permissions check some other way.  

I can see several ways of doing this, but the insistence on using GetDataView() means all of them will be sub-optimal.  Best I can do is give you the tools and let you use them.

**Comment by asierpn** [comment]
No problem, I'm doing it that way now. The option to inherit from EntityTableRepository is enough for us.

**Comment by adrianhall** [comment]
Just checked in the fix here.  The v8 EntityTableRepository is a significant departure from the current EntityTableRepository and was already "virtual" so it could be inherited.  You should check that one out at the same time you are working here.
