### ISSUE TITLE
IAccessControlProvider does not authorize pull requests.

### ISSUE THREAD

**Issue by acidindustries** [Azure/azure-mobile-apps#879]
## Describe the bug

Implemented a basic IAccessControlProvider that check a value with a value passed in the query string. None of the available methods are triggered when the offline client tries to pull data from the server.

## To Reproduce
Implement the following class and register with the TableController

```
public class PublicKeyAuthorizationControlProvider<T> : IAccessControlProvider<T> where T : ITableData
{
    private readonly IHttpContextAccessor _accessor;
    private readonly ILogger _logger;

    public PublicKeyAuthorizationControlProvider(ILogger logger, IHttpContextAccessor accessor)
    {
        _logger = logger;
        _accessor = accessor;
    }

    public Expression<Func<T, bool>> GetDataView()
    {
        return  _ => _accessor.HttpContext.Request.QueryString.Value.Contains("authme");
    }

    public Task<bool> IsAuthorizedAsync(TableOperation op, T entity, CancellationToken token = default)
    {
        return Task.FromResult(_accessor.HttpContext.Request.QueryString.Value.Contains("authme""));
    }

    public virtual async Task PreCommitHookAsync(TableOperation operation, T entity, CancellationToken token = default)
    {
        _logger.LogError("PreCommitHookAsync");
        await Task.CompletedTask;
    }

    public virtual async Task PostCommitHookAsync(TableOperation operation, T entity, CancellationToken token = default)
    {
        _logger.LogError("PostCommitHookAsync");
        await Task.CompletedTask;
    }
}
```

* Make sure to add app.UseAuthorization() to Program.cs.
* Decorate the TableController with [Authorize]

Force a client to pull data from the TableController.

The data is pulled whether or not the querystring contains "authme".

## Expected behavior

The request is denied if it does not contain "authme" in the querystring.

## What platforms?
* Server:
  * .net 8.0
  * ASP.net

* Client:
  * .net 8.0
  * ASP.net

**Comment by fileman** [comment]
Hi, I remember that current version of the library doesn't support .net 8, it is planned for v8.
While you wait reply from @adrianhall, try to reproduce with .net 6

**Comment by adrianhall** [comment]
You are misunderstanding the role of GetDataView() here.  The GetDataView() is an Expression that is applied to an IQueryable form the EF Core environment.  You should just return null there.

The value in IsAuthorizedAsync is “authme”” - there is an extra quote.  I’m not quite certain why this is actually compiling for you.  It shouldn’t.

Can you please provide a GitHub repo with a minimal repro.  I’ll take a look some time next week. (I’m currently recovering from Covid so I’ve not spent any time on the computer this week - this is the first day I’ve even looked at it).

**Comment by acidindustries** [comment]
My mistake, must have happened when I was re-arranging the code to submit the issue. 

I will try to submit a repo to reproduce as soon as possible.

Thanks.

**Comment by adrianhall** [comment]
Looking quickly at this, I can see that `IsAuthorizedAsync()` is called for a query - you can see it here: https://github.com/Azure/azure-mobile-apps/blob/main/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs#L360 - this throws an authentication exception which is handled the same way as all the other HTTP methods.  

So, something must be different about your setup.  I suspect that one of the values within that chain is returning null, so your method is throwing a NullReferenceException instead of returning true/false.  At least, a simple repro of your situation suggests that is the case.

Best idea is to run your repro and set a breakpoint on a place where you can examine the return value of the IsAuthorizedAsync() method in your call while the value is unwrapped away from the Task.Result.  That should tell you clearly what is happening.

In the interim, I'm looking at what we do for this situation.  Since we explicitly look for `result != false` - a null response indicates that the request should be allowed.  (This was done to match prior server versions and changing this is a breaking change).

Calling this blocked / waiting-for-input to see if you validate and can provide a repro if the above does not explain your situation.

**Comment by acidindustries** [comment]
Thanks Adrian, great feedback as always. 

Turns out the TableController overrides QueryAsync without calling the base.QueryAsync(). I believe we can close this issue with the troubleshooting steps your provided.
