### ISSUE TITLE
Update the NSwag package to latest so it can be used in .NET 8

### ISSUE THREAD

**Issue by Arslan007** [Azure/azure-mobile-apps#882]
## Describe the bug

Microsoft.AspNetCore.Datasync.NSwag depends on this NSwag.AspNetCore (13.2.0) and which uses some dependencies that restricts to  < 8.0

## To Reproduce

Try to use NSwag in .NET 8

## Expected behavior

Should be able to use .NET 8 target

## What platforms?

.NET MAUI 8.0

**Comment by henda79** [comment]
[NSwagBugDemo.zip](https://github.com/Azure/azure-mobile-apps/files/14086281/NSwagBugDemo.zip)
I've created a very simple repro based on a new .NET 8 Weather API.

**Comment by adrianhall** [comment]
I'm going to move this to a v8 requirement.  Basically, a (all day) investigation showed that there is a bunch of breaking changes between 13.x and 14.x.  I won't be able to support both net6 and net8 easily without switching up a lot of stuff.

So - live with 13.20.0 for NSwag for now; more service details coming soon on the v8 front.

**Comment by henda79** [comment]
I've built a new version of the Microsoft.AspNetCore.Datasync.NSwag package using version 14.0.2 of NSwag but still on .NET 6 and it no longer gives me the error.

**I have added the NuGet package here but it should only be used for testing until an official release is published.**
[Microsoft.AspNetCore.Datasync.NSwag.1.0.0.zip](https://github.com/Azure/azure-mobile-apps/files/14096983/Microsoft.AspNetCore.Datasync.NSwag.1.0.0.zip)

**Comment by adrianhall** [comment]
Do you want to put a PR in against the repo (make sure you update the tests too)?

**Comment by henda79** [comment]
I'd love to help out Adrian but don't know the procedure for public projects. I'm still learning the testing framework.

All I done to the original source, was update the NSwag nuget to 14.0.2 and then change one line.

```
        public static void AddDatasyncProcessors(this AspNetCoreOpenApiDocumentGeneratorSettings settings)
        {
            settings.OperationProcessors.Add(new DatasyncOperationProcessor());
            settings.SchemaSettings.SchemaProcessors.Add(new DatasyncSchemaProcessor());
        }
```

**Comment by adrianhall** [comment]
Got it - since it's a small change, I'll take a look this afternoon.

For public projects like this,
1. Use the fork button at the top of the Code tab to create a fork in your own account.
2. On your dev machine:
    ```bash
    git clone https://github.com/henda79/azure-mobile-apps
    cd azure-mobile-apps
    git remote add upstream https://github.com/Azure/azure-mobile-apps
    ```

You are now set up to contribute!  `cd sdk\dotnet; .\Datasync.Framework.sln`.  Create a branch (you'll see main in the footer status bar - click on that and create + checkout the new branch), do your changes, run the tests (using Test Explorer), then commit to the new branch and push to your origin.

Now, go back onto your fork of the repo and you'll notice a big banner saying "create a pull request" - it's relatively straight forward from that point on!
